version: '3.3'

services:
   db:
     image: mariadb:10.1
     container_name: mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     command: "--default-authentication-plugin=mysql_native_password"
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASS}

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress
     ports:
       - "8088:80"
     restart: always
     volumes:
       - ./wp-content:/var/www/html/wp-content
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     hostname: ${HOST_URL}
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${DB_USER}
       WORDPRESS_DB_PASSWORD: ${DB_PASS}
       WORDPRESS_DB_NAME: ${DB_NAME}
       VIRTUAL_PORT: 8088
       VIRTUAL_HOST: ${HOST_URL}
       LETSENCRYPT_HOST: ${HOST_URL}
       LETSENCRYPT_EMAIL: ${SUPPORT_EMAIL}
     networks:
       - nginx-proxy
       - default
volumes:
    db_data: {}
networks:
    nginx-proxy:
      external: true
