services:
   db:
     image: mariadb:10.1
     container_name: mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     command: "--default-authentication-plugin=mysql_native_password"
     environment:
       - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
       - MYSQL_DATABASE=${DB_NAME}
       - MYSQL_USER=${DB_USER}
       - MYSQL_PASSWORD=${DB_PASS}

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress
     ports:
       - "8088:80"
     restart: unless-stopped
     volumes:
       - ./wp-content:/var/www/html/wp-content
       - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     hostname: ${VIRTUAL_HOST}
     environment:
       - WORDPRESS_DB_HOST=db:3306
       - WORDPRESS_DB_USER=${DB_USER}
       - WORDPRESS_DB_PASSWORD=${DB_PASS}
       - WORDPRESS_DB_NAME=${DB_NAME}
       - VIRTUAL_PORT
       - VIRTUAL_HOST
       - LETSENCRYPT_HOST
       - LETSENCRYPT_EMAIL
     networks:
       - proxy
       - default
       
volumes:
    db_data: {}

networks:
    proxy:
      external: true
